regex_app/urls.py
from django.urls import path
from.import views

app_name="regex_app"

urlpatterns = [
  path('', views.index, name='index'),
  path('confirm/',views.confirm, name='confirm'),
]

regular_expression/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('regex_app/', include('regex_app.urls')),
    path('admin/', admin.site.urls),
]

regex_app/models.py
from django.db import models

# Create your models here.

regex_app/views.py
from django.shortcuts import render,redirect
import re

# Create your views here.
def index(regex_app):
    return render(regex_app, 'regex_app/index.html')

def confirm(request):
    if request.method == 'POST':
        name = re.sub('\s',"",request.POST.get("name"))
        age = request.POST.get("age")
        zip_code = request.POST.get("zip_code")
        tel = request.POST.get("tel")

        context = {
            "name":name,
            "age":age,
            "zip_code":zip_code,
            "tel":tel,
        }

        error_message = {
            "name":None,
            "age":None,
            "zip_code":None,
            "tel":None,
        }

        #ageの処理
        if not re.match('^[0-9]+$',context["age"]):
            error_message['age'] = 'ageは1〜3桁の半角数字のみで入力して下さい'
            age = None
        #zip_codeの処理
        if not re.match('^\d{3}-?\d{4}$',context["zip_code"]):
            error_message['zip_code'] = 'Zip Codeは全7桁の半角数字を入力して下さい(ハイフンはあってもなくてもよい)。'
            zip_code = None
        #telの処理
        if not re.match('^\d{3}-?\d{4}-?\d{4}$',context["tel"]):
            error_message['tel'] = 'Cell_phoneは全9桁の半角数字を入力して下さい(ハイフンはあってもなくてもよい)。'
            tel = None
        #全て一致した時の処理
        if re.match('^[0-9]+$',context["age"]) and re.match('^\d{3}-?\d{4}$',context["zip_code"]) and re.match('^\d{3}-?\d{4}-?\d{4}$',context["tel"]):
            return render(request,'regex_app/confirm.html',context)
    
    return render(request, 'regex_app/index.html', {'context': context, 'error_message': error_message})

regex_app/templates/regex_app/confirm.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>確認してね</h1>
    <p>{{name}}</p>
    <p>{{age}}</p>
    <p>{{zip_code}}</p>
    <p>{{tel}}</p>
</body>

</html>

regex_app/templates/regex_app/index.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>regex</title>
</head>

<body>
    <h1>登録してね</h1>
    <form action="{% url 'regex_app:confirm' %}" method="POST">
        {% csrf_token %}
        <p>
            <label for="name">Name:
                <input type="text" name="name" id="name" value="{{ context.name }}">
            </label>
        </p>
        {% if error_message.age %}
        <p style="color: red;">{{ error_message.age }}</p>
        {% endif %}
        <p>
            <label for="age">Age:
                <input type="text" name="age" id="age" value="{{context.age}}">
            </label>
        </p>
        {% if error_message.zip_code %}
        <p style="color: red;">{{ error_message.zip_code }}</p>
        {% endif %}
        <p>
            <label for="zip_code">Zip code:
                <input type="text" name="zip_code" id="zip_code" value="{{ context.zip_code }}">
            </label>
        </p>
        {% if error_message.tel %}
        <p style="color: red;">{{ error_message.tel }}</p>
        {% endif %}
        <p>
            <label for="">Cell phone:
                <input type="text" name="tel" id="tel" value="{{context.tel}}">
            </label>
        </p>
        <p>
            <button type="submit">送信</button>
        </p>
    </form>
</body>

</html>